### ISSUE TITLE
Assign role to network health monitor

### ISSUE THREAD

**Issue by dapplion** [gnosischain/consensus-deployment-ansible#50]
Gnosis chain must have a person of team fully commited to detecting network issues in a short timeframe. This infra probably already exists, but client teams and users would benefit from an explicit description of who this team is and what methods do they employ to achieve fast responses.

Nethermind also wants to contribute to that role but must be assumed as a backup resource only.

**Comment by plato-gno** [comment]
Migrated to Notion
https://www.notion.so/Network-Health-Monitoring-75a38b9a3dee467f86d39f3eda9ae4c1
